import avatar from "../../../assets/avatar.png";
export default [
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-purple-1", "bg-purple-3"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-purple-1", "bg-purple-3"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-gray-4", "bg-gray-1"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-purple-1", "bg-purple-3"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-orange-5", "bg-orange-1"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-purple-1", "bg-purple-3"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-gray-4", "bg-gray-1"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-gray-4", "bg-gray-1"],
  },
  {
    title: "Gestão de Demandas PMO",
    department: "GEREL",
    version: "V1",
    status: "Em aberto",
    step: "Definindo necessidades",
    progress: "43%",
    users: [
      {
        name: "Flávia",
        surname: "Braga",
        avatar: null,
      },
      { name: "Tiago", surname: "Ventura", avatar: null },
      { name: "Maria", surname: "Silva", avatar },
    ],
    icon: ["text-orange-5", "bg-orange-1"],
  },
];
